name: Build & Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # needed for PyPI trusted publisher
    steps:
      - uses: actions/checkout@v3
      - name: Install Hatch
        run: pip install hatch
      - name: Build package
        run: hatch build
      - name: Test package
        run: hatch test
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          repository-url: https://test.pypi.org/legacy/
